/** 模块目录 —— 全应用唯一的「有哪些功能」清单（唯一真源）。
 *
 * 路由表、首页磁贴、训练打卡目录都从这里派生；改这里就够了。
 * 每个模块只声明「叫什么、挂哪、怎么加载」，页面实现仍放在 pages/ 下（懒加载，不影响首屏体积）。
 *
 * 约定：
 * - `tile` 默认 true（进首页磁贴）；详情页 / 二级页 / 调试页显式 `tile: false`。
 * - `training: true` 的模块会进训练打卡目录（services/training 的 FEATURES）。
 * - 顺序 = 首页磁贴顺序（组内），保持与原 HomePage.SECTIONS 一致。
 */

import type { SkillModule } from "./types"

// ════════════════════════════ 拼音 ════════════════════════════

const pinyinModules: SkillModule[] = [
  {
    id: "pinyin",
    route: "/pinyin",
    title: "拼音练习",
    icon: "🔤",
    subtitle: "看拼音读，SOE 评测 · 总分≥70 进下一关",
    group: "pinyin",
    load: () => import("../pages/PinyinPracticePage").then((m) => ({ default: m.PinyinPracticePage })),
  },
  {
    id: "pinyin_index",
    route: "/module/pinyin-index",
    title: "拼音表",
    icon: "📖",
    subtitle: "声母 · 韵母 · 整体认读音节 · 点读发声",
    group: "pinyin",
    load: () => import("../pages/PinyinIndexPage").then((m) => ({ default: m.PinyinIndexPage })),
  },
  {
    id: "pinyin_detail",
    route: "/module/pinyin/:id",
    title: "拼音详情",
    icon: "📖",
    group: "pinyin",
    tile: false,
    load: () => import("../pages/PinyinDetailPage").then((m) => ({ default: m.PinyinDetailPage })),
  },
]

// ════════════════════════ 课本字词 ════════════════════════

const textbookModules: SkillModule[] = [
  {
    id: "recognition",
    route: "/module/recognition",
    title: "认字",
    icon: "🔤",
    subtitle: "看图认汉字，跟读发音",
    group: "textbook",
    training: true,
    load: () => import("../pages/RecognitionPage").then((m) => ({ default: m.RecognitionPage })),
  },
  {
    id: "dictation",
    route: "/module/dictation",
    title: "默写",
    icon: "✏️",
    subtitle: "听音写字，检验掌握",
    group: "textbook",
    training: true,
    load: () => import("../pages/DictationPage").then((m) => ({ default: m.DictationPage })),
  },
  {
    id: "word_practice",
    route: "/module/word_practice",
    title: "词语",
    icon: "📚",
    subtitle: "词语跟读与辨析",
    group: "textbook",
    training: true,
    load: () => import("../pages/WordPracticePage").then((m) => ({ default: m.WordPracticePage })),
  },
  {
    id: "english_learning",
    route: "/module/english_learning",
    title: "英语学习",
    icon: "🇬🇧",
    subtitle: "字母 · 拼读 · 视频跟读",
    group: "textbook",
    tile: false,
    training: true,
    load: () => import("../pages/EnglishLearningPage").then((m) => ({ default: m.EnglishLearningPage })),
  },
  {
    id: "letters",
    route: "/module/letters",
    title: "字母表",
    icon: "🔡",
    group: "textbook",
    tile: false,
    load: () => import("../pages/LetterIndexPage").then((m) => ({ default: m.LetterIndexPage })),
  },
  {
    id: "letter_detail",
    route: "/module/letter/:char",
    title: "字母详情",
    icon: "🔡",
    group: "textbook",
    tile: false,
    load: () => import("../pages/LetterDetailPage").then((m) => ({ default: m.LetterDetailPage })),
  },
  {
    id: "phoneme_index",
    route: "/module/phoneme-index",
    title: "音素表",
    icon: "🔊",
    group: "textbook",
    tile: false,
    load: () => import("../pages/PhonemeIndexPage").then((m) => ({ default: m.PhonemeIndexPage })),
  },
  {
    id: "phoneme_detail",
    route: "/module/phoneme/:symbol",
    title: "音素详情",
    icon: "🔊",
    group: "textbook",
    tile: false,
    load: () => import("../pages/PhonemeDetailPage").then((m) => ({ default: m.PhonemeDetailPage })),
  },
  {
    id: "pronounce",
    route: "/module/pronounce/:wordId",
    title: "单词发音",
    icon: "🔊",
    group: "textbook",
    tile: false,
    load: () => import("../pages/PronunciationPage").then((m) => ({ default: m.PronunciationPage })),
  },
]

// ════════════════════════════ 视频 ════════════════════════════

const videoModules: SkillModule[] = [
  {
    id: "video_practice",
    route: "/module/video_practice",
    title: "视频跟读",
    icon: "🎬",
    subtitle: "跟读视频练发音",
    group: "video",
    training: true,
    load: () => import("../pages/VideoPracticePage").then((m) => ({ default: m.VideoPracticePage })),
  },
  {
    id: "subtitle_capture",
    route: "/module/subtitle_capture",
    title: "字幕采集",
    icon: "🎞️",
    subtitle: "框选影片字幕 · 截屏存盘带时间戳",
    group: "video",
    load: () => import("../pages/SubtitleCapturePage").then((m) => ({ default: m.SubtitleCapturePage })),
  },
  {
    id: "quiz_practice",
    route: "/module/quiz_practice",
    title: "随堂测验",
    icon: "📝",
    group: "video",
    tile: false,
    load: () => import("../pages/QuizPracticePage").then((m) => ({ default: m.QuizPracticePage })),
  },
  {
    id: "daily_practice",
    route: "/module/daily_practice",
    title: "每日一练",
    icon: "🏆",
    subtitle: "语文 · 数学 · 英语",
    group: "video",
    tile: false,
    training: true,
    load: () => import("../pages/DailyPracticePage").then((m) => ({ default: m.DailyPracticePage })),
  },
  {
    id: "daily_chinese",
    route: "/module/daily_chinese",
    title: "每日语文",
    icon: "📅",
    group: "video",
    tile: false,
    load: () => import("../pages/DailyChinesePage").then((m) => ({ default: m.DailyChinesePage })),
  },
  {
    id: "daily_english",
    route: "/module/daily_english",
    title: "每日英语",
    icon: "📅",
    group: "video",
    tile: false,
    load: () => import("../pages/DailyEnglishPage").then((m) => ({ default: m.DailyEnglishPage })),
  },
]

// ════════════════════════ 动画学数学 ════════════════════════

const mathModules: SkillModule[] = [
  {
    id: "math_compound_expr",
    route: "/module/math_compound_expr",
    title: "三年级上综合算式动画",
    icon: "🧮",
    subtitle: "动画演示「找→换→查」合并两个算式 · 何时必须加括号 + 易错警示",
    group: "math",
    load: () => import("../pages/MathCompoundExprPage").then((m) => ({ default: m.MathCompoundExprPage })),
  },
  {
    id: "math_equation_move",
    route: "/module/math_equation_move",
    title: "等式变变变",
    icon: "⚖️",
    subtitle: "动画演示移项变号：跨过等号加减互换、乘除互换 · 同侧换位置符号不变",
    group: "math",
    load: () => import("../pages/EquationMovePage").then((m) => ({ default: m.EquationMovePage })),
  },
  {
    id: "math_units",
    route: "/module/math_units",
    title: "长度与质量单位",
    icon: "📏",
    subtitle: "毫米/厘米/分米/米/千米 · 克/千克/吨 —— 切开拼合看懂方向，参照物建立量感",
    group: "math",
    load: () => import("../pages/MathUnitsPage").then((m) => ({ default: m.MathUnitsPage })),
  },
  {
    id: "math_mul_one",
    route: "/module/math_mul_one",
    title: "多位数乘一位数",
    icon: "✏️",
    subtitle: "竖式逐位四拍：乘 → 加进位 → 写 → 进 · 位值点阵看懂为什么从个位乘起",
    group: "math",
    load: () => import("../pages/MathMulOnePage").then((m) => ({ default: m.MathMulOnePage })),
  },
]

// ═══════════════════════════ 学习工具 ═══════════════════════════

const toolModules: SkillModule[] = [
  {
    id: "murmur",
    route: "/module/murmur",
    title: "碎碎念",
    icon: "💬",
    subtitle: "自由表达 → AI 纠错 → 朗读 + 测评",
    group: "tools",
    load: () => import("../pages/MurmurPage").then((m) => ({ default: m.MurmurPage })),
  },
  {
    id: "char_image",
    route: "/module/char_image",
    title: "看图识字",
    icon: "🖼️",
    subtitle: "识字 · 识词 · 识句 · 左右滑动",
    group: "tools",
    training: true,
    load: () => import("../pages/CharImageEntryPage").then((m) => ({ default: m.CharImageEntryPage })),
  },
  {
    id: "wordbook",
    route: "/module/wordbook",
    title: "生词本",
    icon: "📓",
    subtitle: "点读收生字 · 每日间隔复习",
    group: "tools",
    load: () => import("../pages/WordbookPage").then((m) => ({ default: m.WordbookPage })),
  },
  {
    id: "memory_joy",
    route: "/module/memory_joy",
    title: "记忆快乐本",
    icon: "🌟",
    subtitle: "今日字词自动编成小故事",
    group: "tools",
    load: () => import("../pages/MemoryJoyPage").then((m) => ({ default: m.MemoryJoyPage })),
  },
  {
    id: "sentence_practice",
    route: "/module/sentence_practice",
    title: "造句练习",
    icon: "✏️",
    subtitle: "用一个词写句话，AI 老师批改",
    group: "tools",
    load: () => import("../pages/SentencePracticePage").then((m) => ({ default: m.SentencePracticePage })),
  },
  {
    id: "oral_writing",
    route: "/module/oral_writing",
    title: "口述作文",
    icon: "🎙️",
    subtitle: "看图/听题口述表达，AI 评分润色",
    group: "tools",
    training: true,
    load: () => import("../pages/OralWritingPage").then((m) => ({ default: m.OralWritingPage })),
  },
  {
    id: "speech_compose",
    route: "/module/speech_compose",
    title: "AI 对话学语文",
    icon: "🤖",
    subtitle: "一问一答学语文，粘贴文章分句背诵跟读",
    group: "tools",
    load: () => import("../pages/SpeechComposePage").then((m) => ({ default: m.SpeechComposePage })),
  },
  {
    id: "ai_english_talk",
    route: "/module/ai_english_talk",
    title: "AI 英语对话",
    icon: "💬",
    subtitle: "和 AI 用英语聊天，卡住有提示",
    group: "tools",
    load: () => import("../pages/AiEnglishTalkPage").then((m) => ({ default: m.AiEnglishTalkPage })),
  },
  {
    id: "char_map",
    route: "/module/char_map",
    title: "汉字地图",
    icon: "🗺️",
    subtitle: "点亮学过的每一个字",
    group: "tools",
    load: () => import("../pages/CharMapPage").then((m) => ({ default: m.CharMapPage })),
  },
  {
    id: "diary",
    route: "/module/diary",
    title: "成长日记",
    icon: "📖",
    subtitle: "每天一句话，AI 帮你记下来",
    group: "tools",
    load: () => import("../pages/DiaryPage").then((m) => ({ default: m.DiaryPage })),
  },
  {
    id: "radical_game",
    route: "/module/radical_game",
    title: "偏旁魔法屋",
    icon: "🔮",
    subtitle: "声旁猜读音，形旁猜意思",
    group: "tools",
    load: () => import("../pages/RadicalGamePage").then((m) => ({ default: m.RadicalGamePage })),
  },
  {
    id: "courseware_manager",
    route: "/module/courseware_manager",
    title: "课件库",
    icon: "📚",
    subtitle: "上传/管理语数英课件图片",
    group: "tools",
    load: () => import("../pages/CoursewareManagerPage").then((m) => ({ default: m.CoursewareManagerPage })),
  },

  // ── 以下不进首页磁贴：二级页 / 跳转页 ──

  {
    id: "char_image_practice",
    route: "/module/char_image/practice",
    title: "看图识字（练习）",
    icon: "🖼️",
    group: "tools",
    tile: false,
    load: () => import("../pages/CharImagePage").then((m) => ({ default: m.CharImagePage })),
  },
  {
    id: "soe_history",
    route: "/module/soe_history",
    title: "评测历史",
    icon: "📊",
    group: "tools",
    tile: false,
    load: () => import("../pages/SoeHistoryPage").then((m) => ({ default: m.SoeHistoryPage })),
  },
  {
    id: "parent_report",
    route: "/module/parent_report",
    title: "家长周报",
    icon: "📈",
    group: "tools",
    tile: false,
    load: () => import("../pages/ParentReportPage").then((m) => ({ default: m.ParentReportPage })),
  },
  {
    id: "ai_practice",
    route: "/module/ai_practice",
    title: "AI 陪我练",
    icon: "🤖",
    subtitle: "导入主题，AI 多轮引导练习",
    group: "tools",
    tile: false,
    training: true,
    load: () => import("../pages/AiPracticePage").then((m) => ({ default: m.AiPracticePage })),
  },
  {
    id: "ai_practice_chat",
    route: "/module/ai-practice-chat/:sessionId",
    title: "AI 陪练（会话）",
    icon: "🤖",
    group: "tools",
    tile: false,
    load: () => import("../pages/AiPracticeChatPage").then((m) => ({ default: m.AiPracticeChatPage })),
  },
  {
    id: "ai_homework",
    route: "/module/ai_homework",
    title: "AI 作业批改",
    icon: "📷",
    group: "tools",
    tile: false,
    load: () => import("../pages/AiHomeworkPage").then((m) => ({ default: m.AiHomeworkPage })),
  },
  {
    id: "ai_chinese",
    route: "/module/ai_chinese",
    title: "AI 语文识图",
    icon: "📷",
    subtitle: "拍照/粘贴图片识别，语文问答",
    group: "tools",
    tile: false,
    training: true,
    load: () => import("../pages/AiChinesePage").then((m) => ({ default: m.AiChinesePage })),
  },
  {
    id: "ai_english",
    route: "/module/ai_english",
    title: "AI 英语识图",
    icon: "📷",
    group: "tools",
    tile: false,
    load: () => import("../pages/AiEnglishPage").then((m) => ({ default: m.AiEnglishPage })),
  },
  {
    id: "ai_parse_result",
    route: "/module/ai_parse_result",
    title: "识别结果",
    icon: "📄",
    group: "tools",
    tile: false,
    load: () => import("../pages/AiParseResultPage").then((m) => ({ default: m.AiParseResultPage })),
  },
  {
    id: "ai_history",
    route: "/module/ai_history",
    title: "AI 历史",
    icon: "🕘",
    group: "tools",
    tile: false,
    load: () => import("../pages/AiHistoryPage").then((m) => ({ default: m.AiHistoryPage })),
  },
]

// ════════════════════════ 系统页（不在首页） ════════════════════════

const systemModules: SkillModule[] = [
  {
    id: "login",
    route: "/login",
    title: "登录",
    icon: "🔑",
    tile: false,
    guard: "guest",
    load: () => import("../pages/LoginPage").then((m) => ({ default: m.LoginPage })),
  },
  {
    id: "register",
    route: "/register",
    title: "注册",
    icon: "🆕",
    tile: false,
    guard: "guest",
    load: () => import("../pages/RegisterPage").then((m) => ({ default: m.RegisterPage })),
  },
  {
    id: "placeholder",
    route: "/module/:featureId",
    title: "功能占位页",
    icon: "🚧",
    tile: false,
    load: () => import("../pages/PlaceholderPage").then((m) => ({ default: m.PlaceholderPage })),
  },
  {
    id: "soe_demo",
    route: "/soe-demo",
    title: "发音评测（调试）",
    icon: "🎤",
    tile: false,
    load: () => import("../pages/SoeDemoPage").then((m) => ({ default: m.SoeDemoPage })),
  },
]

/** 全部模块（顺序无关；路由/磁贴各自的顺序由 registry 决定） */
export const ALL_MODULES: SkillModule[] = [
  ...pinyinModules,
  ...textbookModules,
  ...videoModules,
  ...mathModules,
  ...toolModules,
  ...systemModules,
]
